const links = {
  boltGuide: 'https://www.youtube.com/playlist?list=PLQFx_vtbR0SioPtXeXO2j8aAPaUb3TOYU',
  calendar: 'https://youtu.be/iBThwch_Tn0',
  registration: 'https://controlfleet.ro/onboarding/participatiune/5b2df208d1b9a87844e7fe9508fea2d572d6d9ac503bd2382213a0416f52bb32',
  telegramGuide: 'https://www.youtube.com/playlist?list=PLLEIvJ6LBUOs',
  telegram: 'https://t.me/eatsdelivery_bot?start=onboarding'
};
// Activăm timerele înainte de lansarea finală.
const timersEnabled = false;

const questions = [
  ['Ca și curier nou, ce tipuri de comenzi vei primi?', ['Doar comenzi achitate online de către clienți','Doar comenzi unde curierul colectează cash de la clienți','Doar comenzi cu distanță maximă de 3 km','Toate tipurile de comenzi'], [0]],
  ['Cum afli când comenzile cash sunt deblocate pe contul tău?', ['Îmi va spune administratorul flotei','Voi primi mail de la Bolt Food','Voi afla atunci când îmi intră o comandă cash'], [1]],
  ['Care sunt avantajele comenzilor cash?', ['Posibilitatea de a primi mai mult bacșiș numerar de la clienți','Disponibilitate la mai multe comenzi din mai multe categorii','Rămân cu mai mulți bani pe care îi păstrez'], [0,1]],
  ['Cum ții tips-ul primit cash separat de balanța din aplicație?', ['Schimb suma din balanța numerar după fiecare comandă','Introduc suma fixă de primit de la client; restul rămâne tips-ul meu','Îmi va spune clientul ce să fac'], [1]],
  ['Ce semnifică balanța numerar din aplicație?', ['Suma tuturor tranzacțiilor cash efectuate în activitatea la livrări','Banii pe care îi voi primi la salariu','Toți banii încasați la livrări'], [0]],
  ['Ce semnifică atunci când balanța numerar e afișată cu minus?', ['Administratorul flotei se va ocupa','Bolt Food îmi datorează bani','Datorez bani la Bolt Food și trebuie să-i returnez'], [2]],
  ['Ce se întâmplă dacă ajungi la o sumă mare negativă în balanță?', ['Voi primi mai multe comenzi cu plată la preluare','Contul este blocat complet','Voi fi dat în judecată','Comenzile unde colectez cash sunt blocate până scad sub prag'], [0,3]],
  ['Care este procedura corectă pentru a depune banii cash din balanță?', ['Se ocupă administratorul flotei','Fac transfer bancar folosind datele din aplicație','Îmi pun datele cardului în aplicație și achit direct cu cardul','Voi fi contactat când trebuie depuși'], [2]],
  ['Care metodă de depunere se actualizează cel mai rapid?', ['Transfer bancar','Cu cardul în aplicație','Se ocupă administratorul flotei'], [1]],
  ['Când trebuie să achiți la preluarea unei comenzi de la restaurant?', ['Oricând vreau să îmi reglez balanța','Doar când e indicat în aplicație','Doar când îmi cer cei de la restaurant'], [1]],
  ['Ce ai de făcut la o comandă cash?', ['Plătesc mereu la preluare și colectez mereu de la client','Nu plătesc nimic, dar primesc bani de la client','Plătesc la preluare fără să colectez','Toate variantele, în funcție de indicațiile aplicației'], [3]],
  ['Cum afli că o comandă implică tranzacții cash?', ['Mă informează restaurantul și clientul','Îmi apare înainte să accept','Văd în detaliile comenzii după ce am acceptat-o'], [2]],
  ['Cum afli dacă clientul trebuie să plătească numerar?', ['În detaliile comenzii, după ce am marcat că am ridicat-o','Mă uit în balanță','Clientul îmi arată telefonul'], [0]],
  ['Ce faci când aplicația indică să achiți o sumă la restaurant?', ['Pregătesc suma, o predau, glisez plata și aștept confirmarea restaurantului','Plătesc la POS, iau comanda și plec','Predau suma, iau singur comanda și plec'], [0]],
  ['Ce se întâmplă dacă restaurantul nu confirmă plata în aplicație?', ['Nu pot procesa mai departe comanda și nu apar detaliile clientului','Nu trebuie să confirme','Restaurantul rămâne cu banii și eu cu comanda'], [0]],
  ['Când îți apar informațiile despre client?', ['După ce am ridicat comanda și am marcat preluarea','Imediat după acceptare','Restaurantul mi le oferă după ridicare'], [0]],
  ['Ce faci când predai o comandă cash clientului?', ['Cer banii, îi verific, predau comanda și introduc suma exactă din aplicație; surplusul este tips','Cer banii, predau comanda și introduc toată suma primită'], [0]],
  ['Ce factori influențează reputația contului de curier?', ['Acceptarea, rating-ul, realocarea/anularea și feedback-ul primit','Vehiculul și vremea','Intervalele de lucru și tips-urile'], [0]]
].map(([text, options, correct], id) => ({ id, text, options, correct }));

const calendarQuestions = [
  { text:'Când efectuează flota plățile?', options:['Săptămânal, în fiecare zi de Marți','Săptămânal, în fiecare zi de Vineri după săptămâna lucrată','Lunar, în prima zi a lunii','Lunar, la încheierea fiecărei luni'], correct:1 },
  { text:'Cum calculează Bolt Food săptămânile de lucru?', options:['După calendar: 1–7, 8–15, 16–22, 23–30','Luni la ora 00:00 începe, Duminică la ora 23:59 se încheie','De Vineri până Vineri'], correct:1 }
];

const blank = { screen:'welcome', boltUntil:null, retryUntil:null, boltSet:null, calendarUntil:null, registrationVisited:false, telegramUntil:null };
function playlistPlayer(id,title,firstVideoId=''){const src=firstVideoId?`https://www.youtube.com/embed/${firstVideoId}?list=${id}&index=1`:`https://www.youtube.com/embed/videoseries?list=${id}`;return `<div class="playlist-player"><iframe src="${src}" title="${title}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`}
function videoPlayer(id,title){return `<div class="playlist-player"><iframe src="https://www.youtube-nocookie.com/embed/${id}" title="${title}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`}
const savedSession = JSON.parse(localStorage.getItem('eats-onboarding-v1') || 'null');
let state = { ...blank };
const app = document.querySelector('#app');
function save(){ localStorage.setItem('eats-onboarding-v1', JSON.stringify(state)); }
function go(screen){ state.screen=screen; save(); render(); }
function startFresh(){ state={ ...blank, freshStarted:true }; save(); render(); }
function resume(){ state={ ...blank, ...savedSession }; save(); render(); }
function open(url){ window.open(url, '_blank', 'noopener'); }
function remaining(until){ return timersEnabled ? Math.max(0, until-Date.now()) : 0; }
function time(ms){ const s=Math.ceil(ms/1000); return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; }
function lockedLabel(label, until){ if(!until || remaining(until)===0) return label; setTimeout(render, 1000); return `${label} · ${time(remaining(until))}`; }
function setProgress(step){ document.querySelectorAll('.step').forEach((item,index)=>{ const current=index===step-1; item.classList.toggle('current',current); item.classList.toggle('complete',index<step-1); item.toggleAttribute('aria-current',current); }); document.querySelectorAll('.step-connector').forEach((line,index)=>line.classList.toggle('complete',index<step-1)); }
function action(label, handler, secondary=false, disabled=false){ return `<button class="button ${secondary?'secondary':''}" ${disabled?'disabled':''} onclick="${handler}">${label}</button>`; }
function ext(label,url,secondary=false){ return `<a class="button ${secondary?'secondary':''}" href="${url}" target="_blank" rel="noopener">${label}</a>`; }
function randomSet(){ return [...questions].sort(()=>Math.random()-.5).slice(0,10).map(q=>q.id); }
function boltReady(){ return (!state.boltUntil || remaining(state.boltUntil)===0) && (!state.retryUntil || remaining(state.retryUntil)===0); }

function welcome(){ setProgress(1); const canResume=!state.freshStarted&&savedSession&&savedSession.screen&&savedSession.screen!=='welcome'&&savedSession.screen!=='done'; const modal=canResume?`<div class="resume-overlay" role="dialog" aria-modal="true"><div class="resume-dialog"><p>E posibil să fi fost scos din sesiune în timp ce o completai. Vrei să reiei procesul de unde ai rămas în sesiunea anterioară?</p><div class="actions">${action('Da, continui de unde am rămas','resume()')}${action('Nu, reiau procesul de la capăt','startFresh()',true)}</div></div></div>`:''; return `<div class="welcome-content"><span class="eyebrow">Bun venit</span><h1>Începem onboarding-ul.</h1><p class="lead">Bine te-am găsit la procesul de onboarding. Urmează să treci prin câțiva pași care au ca scop atât înregistrarea în flota noastră și în grupurile de comunicare, cât și o informare generală.</p><p>Treci prin fiecare pas și asigură-te că citești tot, nu omiți nimic important și acorzi atenția necesară acestui proces, pentru a te integra cât mai bine.</p><div class="actions">${action('Mergi mai departe',"go('bolt')")}</div></div>${modal}`; }
function bolt(){ setProgress(2); const active=state.boltUntil && remaining(state.boltUntil)>0; return `<span class="eyebrow">Pasul 2 · Bolt Food</span><h1>Ghidul curierului.</h1><p>Platforma cu care vei începe este Bolt Food. Urmărește playlist-ul ghidului de mai jos pentru a înțelege aplicația de curier, numerarul colectat, tipurile de comenzi și multe altele.</p><p>Playlist-ul are aproximativ 10 minute. La pasul următor vei avea un quiz obligatoriu.</p>${playlistPlayer('PLQFx_vtbR0SioPtXeXO2j8aAPaUb3TOYU','Ghidul Curierului la Bolt Food')}<div class="notice"><strong>Important:</strong> Mulți curieri omit informarea și întâmpină probleme ulterior. Revino aici după ce ai urmărit ghidul.</div><div class="actions">${action(lockedLabel('Începe Quiz-ul',state.boltUntil),"startBolt()",false,active)}</div>`; }
function startBolt(){ if(!boltReady())return; state.boltSet=randomSet(); state.boltAnswers={}; state.boltResult=null; go('boltQuiz'); }
function boltQuiz(){ setProgress(2); const set=(state.boltSet||randomSet()).map(id=>questions[id]); state.boltSet=set.map(q=>q.id); save(); const done=state.boltResult; return `<span class="eyebrow">Pasul 2 · Quiz Bolt Food</span><h1>Verifică ce ai reținut.</h1><p class="quiz-intro">Răspunde la cele 10 întrebări. Trebuie să ai cel puțin 8 răspunsuri corecte. Unele întrebări au mai multe răspunsuri corecte.</p>${set.map((q,i)=>question(q,i,true,done)).join('')} ${done?boltOutcome():`<div class="actions">${action('Finalizează Quiz-ul','submitBolt()',false,!allAnswered(set))}</div>`}`; }
function question(q,n,multi,result){ const chosen=(state.boltAnswers||{})[q.id]||[]; return `<fieldset class="question"><legend>${n+1}. ${q.text}</legend><div class="options">${q.options.map((o,i)=>{ const cls=result ? (q.correct.includes(i)?'correct':chosen.includes(i)?'incorrect':'') : ''; return `<label class="option ${cls}"><input ${result?'disabled':''} type="${multi?'checkbox':'radio'}" name="q${q.id}" value="${i}" ${chosen.includes(i)?'checked':''} onchange="selectBolt(${q.id},${i},${multi})"><span>${o}</span></label>` }).join('')}</div>${result&&!same(chosen,q.correct)?`<p class="answer-note">Răspuns corect: ${q.correct.map(i=>q.options[i]).join(' · ')}</p>`:''}</fieldset>`; }
function selectBolt(id,index,multi){ const a=state.boltAnswers||{}; const now=a[id]||[]; a[id]=multi?(now.includes(index)?now.filter(x=>x!==index):[...now,index]):[index]; state.boltAnswers=a; save(); render(); }
function same(a,b){ return a.length===b.length && a.every(x=>b.includes(x)); }
function allAnswered(set){ return set.every(q=>(state.boltAnswers||{})[q.id]?.length); }
function submitBolt(){ const set=state.boltSet.map(id=>questions[id]); if(!allAnswered(set))return; state.boltResult=set.filter(q=>same(state.boltAnswers[q.id],q.correct)).length; save(); render(); }
function boltOutcome(){ const score=state.boltResult; if(score>=8) return `<div class="result"><h2>Ai trecut quiz-ul!</h2><p>Ai răspuns corect la <strong>${score}/10</strong> întrebări. Felicitări! Acum poți trece la pasul următor.</p><div class="actions">${action('Mergi mai departe',"go('calendar')")}</div></div>`; if(!state.retryUntil&&timersEnabled){state.retryUntil=Date.now()+300000;save();} const active=state.retryUntil&&remaining(state.retryUntil)>0; return `<div class="result fail"><h2>Mai încearcă o dată.</h2><p>Ai răspuns corect la <strong>${score}/10</strong> întrebări. Urmărește din nou ghidul și încearcă din nou cu mai multă atenție.</p><div class="actions">${ext('Deschide din nou ghidul',links.boltGuide,true)}${action(lockedLabel('Reia Quiz-ul',state.retryUntil),'retryBolt()',false,active)}</div></div>`; }
function retryBolt(){ if(state.retryUntil&&remaining(state.retryUntil)>0)return; state.retryUntil=null; state.boltUntil=null; state.boltSet=randomSet(); state.boltAnswers={}; state.boltResult=null; save(); render(); }
function calendar(){ setProgress(3); const active=state.calendarUntil&&remaining(state.calendarUntil)>0; return `<span class="eyebrow">Pasul 3 · Plăți</span><h1>Calendarul de plată.</h1><p>Cu siguranță te interesează ciclul de plată al flotei noastre. Cel mai ușor mod de a-ți oferi aceste informații este printr-un video, explicat direct pe calendar.</p><p>Urmărește video-ul, apoi revino aici pentru a completa pașii următori.</p>${videoPlayer('iBThwch_Tn0','Calendarul de Plată Eats Delivery')}<div class="actions">${action(lockedLabel('Mergi mai departe',state.calendarUntil),"go('calendarQuiz')",false,active)}</div>`; }
function calendarQuiz(){ setProgress(3); const done=state.calendarResult; const complete=calendarQuestions.every((_,i)=>Number.isInteger(state.calendarAnswers?.[i])); return `<span class="eyebrow">Pasul 3 · Quiz Calendar</span><h1>Un scurt control al informațiilor.</h1><p>Răspunde la cele două întrebări. Vei vedea imediat răspunsurile corecte.</p>${calendarQuestions.map((q,i)=>calendarQuestion(q,i,done)).join('')}${done?`<div class="actions">${action('Mergi mai departe',"go('registration')")}</div>`:`<div class="actions">${action('Verifică răspunsurile','submitCalendar()',false,!complete)}</div>`}`; }
function calendarQuestion(q,n,done){const v=state.calendarAnswers?.[n];return `<fieldset class="question"><legend>${n+1}. ${q.text}</legend><div class="options">${q.options.map((o,i)=>`<label class="option ${done ? (i===q.correct ? 'correct' : i===v ? 'incorrect' : '') : ''}"><input type="radio" name="cal${n}" ${done?'disabled':''} ${i===v?'checked':''} onchange="selectCalendar(${n},${i})"><span>${o}</span></label>`).join('')}</div>${done&&v!==q.correct?`<p class="answer-note">Răspuns corect: ${q.options[q.correct]}</p>`:''}</fieldset>`}
function selectCalendar(n,v){state.calendarAnswers=state.calendarAnswers||[];state.calendarAnswers[n]=v;save();render();} function submitCalendar(){state.calendarResult=true;save();render();}
function registration(){setProgress(4);return `<span class="eyebrow">Pasul 4 · Înregistrare</span><h1>Înregistrează-te în sistem.</h1><p>Acum că ai toate informațiile necesare, urmează să completezi onboarding-ul: procesul în care îți introduci datele personale în sistemul nostru și intri în procesul de înregistrare.</p><p>Apasă pe butonul de mai jos pentru a începe, apoi revino aici pentru a continua.</p><div class="actions">${state.registrationVisited?action('Mergi mai departe',"go('telegram')"):`<a class="button" href="${links.registration}" target="_blank" rel="noopener" onclick="registered()">Înregistrează-te</a>`}</div>`}
function registered(){state.registrationVisited=true;save();render();}
function telegram(){setProgress(5);const active=state.telegramUntil&&remaining(state.telegramUntil)>0;return `<span class="eyebrow">Pasul 5 · Comunitate</span><h1>Bun venit pe Telegram.</h1><p>Flota noastră își desfășoară comunicarea pe Telegram. Acolo găsești comunitatea, canalul de anunțuri și botul nostru cu informații și funcții automate.</p><p>Dacă ai nevoie de ajutor, playlist-ul de introducere îți arată cum să îți creezi și folosești contul, precum și sistemele noastre de comunicare.</p>${playlistPlayer('PLLEIvJ6LBUOs','Ghid de introducere pe Telegram','juBx-JwoBaA')}<div class="actions">${ext('Intră în comunitatea flotei pe Telegram',links.telegram,true)}${action(lockedLabel('Finalizează onboarding-ul',state.telegramUntil),"go('done')",false,active)}</div>`}
function done(){setProgress(5);return `<div class="final"><div class="check">✓</div><span class="eyebrow">Onboarding finalizat</span><h1>Mulțumim!</h1><p class="lead">Cererea ta a fost înregistrată. Vei primi curând următorii pași, referitori la activare.</p><p>Îți urăm bun venit și sperăm să fie o colaborare cât mai reușită, de toate părțile!</p></div>`}
function render(){if(timersEnabled&&state.screen==='bolt'&&!state.boltUntil){state.boltUntil=Date.now()+300000;save()}if(timersEnabled&&state.screen==='calendar'&&!state.calendarUntil){state.calendarUntil=Date.now()+180000;save()}if(timersEnabled&&state.screen==='telegram'&&!state.telegramUntil){state.telegramUntil=Date.now()+120000;save()} app.innerHTML=({welcome,bolt,boltQuiz,calendar,calendarQuiz,registration,telegram,done}[state.screen]||welcome)();}
render();
